default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution to testers"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_path: "..\\build\\app\\outputs\\flutter-apk\\app-production-release.apk",
      testers: ENV["FIREBASE_TESTERS"],
      release_notes: "Android firebase app distribution lane release notes"
    )
  end
end
